## References:
## - https://github.com/othomantegazza/milano-air-quality/blob/main/.github/workflows/publish.yml
## - https://quarto.org/docs/publishing/github-pages.html
name: Quarto Publish

on:
  schedule:
    - cron: '0 6 * * 1'
  workflow_dispatch:

jobs:
  build-deploy:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      pages: write
      id-token: write
    env:
      GITHUB_PAT: ${{ secrets.GEEKS_WHO_DRINK_TOKEN }}
      RENV_PATHS_ROOT: ~/.local/share/renv
    steps:
      - name: Check out repository
        uses: actions/checkout@v4 

      - name: Set up Quarto
        uses: quarto-dev/quarto-actions/setup@v2
        with: 
          version: 1.4.451
          
      - name: Setup R
        uses: r-lib/actions/setup-r@v2
        with:
          r-version: '4.2.0'
      
      ## for curl and leaflet
      - name: Install System Dependecies
        run: |
          sudo apt-get update
          sudo apt-get install libcurl4-openssl-dev libudunits2-dev libgdal-dev libgeos-dev libproj-dev 
      
      ## basically what is in r-lib/actions/renv@v2, but it never works for some reason
      - name: Get R and OS version
        id: get-version
        run: |
          cat("os-version=", sessionInfo()$running, "\n", file = Sys.getenv("GITHUB_OUTPUT"), sep = "", append = TRUE)
          cat("r-version=", R.Version()$version.string, "\n", file = Sys.getenv("GITHUB_OUTPUT"), sep = "", append = TRUE)
        shell: Rscript {0}
        
      - name: Cache packages
        uses: actions/cache@v3
        with:
          path: ${{ env.RENV_PATHS_ROOT }}
          key: ${{ steps.get-version.outputs.os-version }}-${{ steps.get-version.outputs.r-version }}-${{ hashFiles('**/renv.lock') }}
          restore-keys: ${{ steps.get-version.outputs.os-version }}-${{ steps.get-version.outputs.r-version }}-
            
      - name: Restore packages
        shell: Rscript {0}
        run: |
          if (!requireNamespace("renv", quietly = TRUE)) install.packages("renv")
          renv::restore()

      - name: Render and publish 
        uses: quarto-dev/quarto-actions/publish@v2
        with:
          render: true
          target: gh-pages
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
