## Reference: https://github.com/MarketingPipeline/Python-Selenium-Action
name: Scrape Geeks Who Drink venues

on:
  schedule:
    - cron: '0 6 * * 1'
  workflow_dispatch:

jobs:
  scrape:
    runs-on: ubuntu-latest
    env:
      GEEKS_WHO_DRINK_TOKEN: ${{ secrets.GEEKS_WHO_DRINK_TOKEN }}
    steps:
      - name: Check out repository
        uses: actions/checkout@v3
        
      # - name: Remove previous chrome instances on runner 
      #   run: sudo apt purge google-chrome-stable
        
      ## https://github.com/marketplace/actions/install-poetry-action
      - name: Set up python
        id: setup-python
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'
          cache: 'pip'
          
      - name: Install and configure Poetry
        uses: snok/install-poetry@v1
        with:
          version: 1.5.0
          virtualenvs-create: true
          virtualenvs-in-project: true
          installer-parallel: true
          
      - name: Load cached venv
        id: cached-poetry-dependencies
        uses: actions/cache@v3
        with:
          path: .venv
          key: venv-${{ runner.os }}-${{ steps.setup-python.outputs.python-version }}-${{ hashFiles('**/poetry.lock') }}
      
      - name: Install dependencies
        if: steps.cached-poetry-dependencies.outputs.cache-hit != 'true'
        run: poetry install --no-interaction --no-root
        
      - name: Install project
        run: poetry install --no-interaction
        
      - name: Scrape venues
        run: python scripts/0-scrape-geekswhodrink-venues.py

