name: Scrape new Geeks Who Drink quiz results

on:
  schedule:
    - cron: '0 8 * * *'
  workflow_dispatch:

jobs:
  scrape-new-geekshowdrink-quiz-results:
    ## Don't use macOS? https://github.com/actions/runner-images/issues/602
    runs-on: ubuntu-latest
    env:
      GITHUB_PAT: ${{ secrets.GEEKS_WHO_DRINK_TOKEN }}
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        
      - name: Setup R 
        uses: r-lib/actions/setup-r@v2
        
      - name: Install R Dependencies
        uses: r-lib/actions/setup-renv@v2
        with:
          cache-version: 1
        
      - name: Scrape stale Geeks Who Drink quiz results
        run: Rscript -e 'source(file.path("R", "1-scrape-new-geekswhodrink.R"), echo = FALSE)'
