## Reference: https://github.com/MarketingPipeline/Python-Selenium-Action
name: Scrape venues

on:
  schedule:
    - cron: '0 6 * * 1'
  workflow_dispatch:

jobs:
  scrape-venues:
    runs-on: ubuntu-latest
    env:
      GEEKS_WHO_DRINK_TOKEN: ${{ secrets.GEEKS_WHO_DRINK_TOKEN }}
    steps:
      - name: Check out repository
        uses: actions/checkout@v3
        
      # - name: Remove previous chrome instances on runner 
      #   run: sudo apt purge google-chrome-stable
        
      ## https://github.com/marketplace/actions/install-poetry-action
      - name: Set up python
        id: setup-python
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'
          cache: 'pip'
          
      - name: Install and configure Poetry
        uses: snok/install-poetry@v1
        with:
          version: 1.5.0
          virtualenvs-create: true
          virtualenvs-in-project: true
          installer-parallel: true
          
      - name: Load cached venv
        id: cached-poetry-dependencies
        uses: actions/cache@v3
        with:
          path: .venv
          key: venv-${{ runner.os }}-${{ steps.setup-python.outputs.python-version }}-${{ hashFiles('**/poetry.lock') }}
      
      - name: Install dependencies
        if: steps.cached-poetry-dependencies.outputs.cache-hit != 'true'
        run: poetry install --no-interaction --no-root
        
      - name: Install project
        run: poetry install --no-interaction
        
      - name: Scrape venues
        run: python scripts/0-scrape-venues.py
        
  scrape-venue-info:
    ## Don't use macOS? https://github.com/actions/runner-images/issues/602
    runs-on: ubuntu-latest
    env:
      GITHUB_PAT: ${{ secrets.GEEKS_WHO_DRINK_TOKEN }}
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        
      - name: Setup R 
        uses: r-lib/actions/setup-r@v2
      
      ## for curl and leaflet
      ## TODO: Make a separate renv profile for the dashboard
      - name: Install System Dependecies
        run: |
          sudo apt-get update
          sudo apt-get install libcurl4-openssl-dev libudunits2-dev libgdal-dev libgeos-dev libproj-dev
          
      - name: Install R Dependencies
        uses: r-lib/actions/setup-renv@v2
        with:
          cache-version: 1
        
      - name: Scrape venue info
        run: Rscript -e 'source(file.path("scripts", "1-scrape-venue-info.R"), echo = FALSE)'
