name: test

on:
  schedule:
    - cron: '0 8 * * *'
  workflow_dispatch:

jobs:
  test:
    ## Don't use macOS? https://github.com/actions/runner-images/issues/602
    runs-on: ubuntu-latest
    env:
      GITHUB_PAT: ${{ secrets.GEEKS_WHO_DRINK_TOKEN }}
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        
      - name: Setup R 
        uses: r-lib/actions/setup-r@v2
      
      ## for curl and leaflet
      ## TODO: Make a separate renv profile for the dashboard
      - name: Install System Dependecies
        run: |
          sudo apt-get update
          sudo apt-get install libcurl4-openssl-dev libudunits2-dev libgdal-dev libgeos-dev libproj-dev
          
      - name: Install R Dependencies
        uses: r-lib/actions/setup-renv@v2
        with:
          cache-version: 1
        
      - name: Scrape quiz results
        run: Rscript -e 'source(file.path("scripts", "test.R"), echo = FALSE)'
