name: test

on:
  push:
    branches:
      - '*'
  workflow_dispatch:

jobs:
  test:
    ## Don't use macOS? https://github.com/actions/runner-images/issues/602
    runs-on: ubuntu-latest
    env:
      GITHUB_PAT: ${{ secrets.GEEKS_WHO_DRINK_TOKEN }}
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        
      - name: Setup R 
        uses: r-lib/actions/setup-r@v2
        with:
          r-version: '4.2.0'
          
      ## for curl
      ## TODO: Make a separate renv profile for the dashboard
      - name: Install System Dependecies
        run: |
          sudo apt-get update
          sudo apt-get install libcurl4-openssl-dev
        
      - name: Install R Dependencies
        uses: r-lib/actions/setup-renv@v2
        with:
          cache-version: 1
          profile: '"dev"'

      - name: test
        run: Rscript -e 'source(file.path("scripts", "test.R"), echo = FALSE)'
