name: test

on:
  workflow_dispatch:

jobs:
  test:
    ## Don't use macOS? https://github.com/actions/runner-images/issues/602
    runs-on: windows-latest
    env:
      GITHUB_PAT: ${{ secrets.GEEKS_WHO_DRINK_TOKEN }}
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        
      - name: Setup R 
        uses: r-lib/actions/setup-r@v2
        with:
          r-version: '4.2.0'

      - name: Install R Dependencies
        uses: r-lib/actions/setup-renv@v2
        with:
          cache-version: 1
          profile: '"dev"'

      - name: Scrape quiz results
        run: Rscript -e 'source(file.path("scripts", "test.R"), echo = FALSE)'
