name: Update artifacts

on:
  schedule:
    - cron: '0 12 * * *'
  workflow_dispatch:

jobs:
  update-artifacts:
    runs-on: ubuntu-latest
    env:
      GEEKS_WHO_DRINK_TOKEN: ${{ secrets.GEEKS_WHO_DRINK_TOKEN }}
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        
      - name: Setup R 
        uses: r-lib/actions/setup-r@v2
        with:
          r-version: '4.2.0'

      - name: Install R Dependencies
        uses: r-lib/actions/setup-renv@v2
        with:
          cache-version: 1
          profile: '"dev"'

      - name: Create supplementary artifacts
        run: Rscript -e 'source(file.path("scripts", "2-create-supplementary-artifacts.R"), echo = FALSE)'

      - name: Scrape quiz results
        run: Rscript -e 'source(file.path("scripts", "3-generate-dashboard-artifacts.R"), echo = FALSE)'
